INSERT INTO "user"
    (
        user_id,
        first_name,
        middle_name,
        last_name,
        state_name,
        country_name,
        address1,
        address2,
        city,
        zip,
        activation_code,
        member_since,
        handle,
        email,
        status,
        last_login,
        image,
        home_phone,
        work_phone,
        modify_date,
        handle_lower,
        competition_country_name,
        srm_rating,
        srm_num_contests,
        mm_rating,
        mm_num_contests,
        srm_last_competition_date,
        mm_last_competition_date,
        conceptualization_rating,
        conceptualization_num_contests,
        specification_rating,
        specification_num_contests,
        architecture_rating,
        architecture_num_contests,
        component_design_rating,
        component_design_num_contests,
        component_development_rating,
        component_development_num_contests,
        assembly_rating,
        assembly_num_contests,
        code_rating,
        code_num_contests,
        F2F_rating,
        F2F_num_contests,
        test_scenario_rating,
        test_scenario_num_contests,
        test_script_rating,
        test_script_num_contests,
        ui_prototype_rating,
        ui_prototype_num_contests,
        ria_build_rating,
        ria_build_num_contests,
        content_rating,
        content_num_contests,
        total_earnings ,
        total_prizes ,
        total_review_earnings ,
        total_tournament_earnings ,
        total_dr_earnings ,
        total_copilot_earnings ,
        reg_source,
        utm_source,
        utm_medium,
        utm_campaign,
        create_date
    )

VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);
